[project]
name = "android-mcp"
version = "0.1.0"
description = "An MCP server for android automation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "pillow>=11.1.0",
    "pure-python-adb>=0.3.0.dev0",
    "pyyaml>=6.0.2",
]
